//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAPA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAPA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Expression_of_the_Emotions_Figure_4 {
            get {
                object obj = ResourceManager.GetObject("Expression_of_the_Emotions_Figure_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///about
        ///above
        ///absolutely
        ///abt
        ///across
        ///actually
        ///after
        ///afterwards
        ///again
        ///against
        ///ahead
        ///aint
        ///ain&apos;t
        ///all
        ///almost
        ///alone
        ///along
        ///already
        ///also
        ///altho
        ///although
        ///always
        ///am
        ///amid
        ///amidst
        ///among*
        ///amoungst
        ///an
        ///and
        ///another
        ///any
        ///anybod*
        ///anyhow
        ///anymore
        ///anyone*
        ///anything
        ///anyway*
        ///anywhere
        ///apparently
        ///are
        ///arent
        ///aren&apos;t
        ///around
        ///as
        ///at
        ///atop
        ///away
        ///awhile
        ///back
        ///barely
        ///basically
        ///bc
        ///be
        ///became
        ///because
        ///become
        ///becomes
        ///becoming
        ///been
        ///before
        ///beforehand
        ///behind
        ///being
        ///below
        ///beneath
        ///beside
        ///besid [rest of string was truncated]&quot;;.
        /// </summary>
        public static string function_word_list {
            get {
                return ResourceManager.GetString("function_word_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol	Type	Valence	Arousal	Dominance
        ///aardvark	word	6.26	2.41	4.27
        ///abalone	word	5.3	2.65	4.95
        ///abandon	word	2.84	3.73	3.32
        ///abandonment	word	2.63	4.95	2.64
        ///abbey	word	5.85	2.2	5
        ///abdomen	word	5.43	3.68	5.15
        ///abdominal	word	4.48	3.5	5.32
        ///abduct	word	2.42	5.9	2.75
        ///abduction	word	2.05	5.33	3.02
        ///abide	word	5.52	3.26	5.33
        ///abiding	word	5.57	3.59	6.6
        ///ability	word	7	4.85	6.55
        ///abject	word	4	3.94	4.35
        ///ablaze	word	5.15	6.75	4.58
        ///able	word	6.64	3.38	6.17
        ///abnormal	word	3.53	4.48	4.7
        ///abnormality	word	3.05	5	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ratings_Warriner_et_al {
            get {
                return ResourceManager.GetString("Ratings_Warriner_et_al", resourceCulture);
            }
        }
    }
}
